/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframeproject;


import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author joabe
 */
public class JFrame4Project extends javax.swing.JFrame {

String resp;
int idade;

    /**
     * Creates new form JFrame4Project
     */
    public JFrame4Project() {
        initComponents();
        Calendar c = Calendar.getInstance();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        aluno = new javax.swing.JTextField();
        serie = new javax.swing.JTextField();
        curso = new javax.swing.JTextField();
        Natal = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        okay = new javax.swing.JButton();
        Ano = new javax.swing.JLabel();
        Escola = new javax.swing.JLabel();
        Curso = new javax.swing.JLabel();
        ICON = new javax.swing.JLabel();
        Aluno = new javax.swing.JLabel();
        Serie = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(136, 181, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jPanel1.setForeground(new java.awt.Color(255, 20, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aluno.setBorder(new javax.swing.border.SoftBevelBorder(0));
        aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alunoActionPerformed(evt);
            }
        });
        jPanel1.add(aluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 299, 40));

        serie.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel1.add(serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 300, 40));

        curso.setBorder(new javax.swing.border.SoftBevelBorder(0));
        curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cursoActionPerformed(evt);
            }
        });
        jPanel1.add(curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 300, 40));

        Natal.setFont(new java.awt.Font("FreesiaUPC", 1, 18)); // NOI18N
        Natal.setText("Data de Nascimento");
        Natal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NatalActionPerformed(evt);
            }
        });
        jPanel1.add(Natal, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 460, 140, 40));

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel1.add(cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(674, 576, -1, -1));

        okay.setText("Okay");
        okay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okayActionPerformed(evt);
            }
        });
        jPanel1.add(okay, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 576, -1, -1));

        Ano.setFont(new java.awt.Font("Yu Gothic Medium", 1, 24)); // NOI18N
        Ano.setForeground(new java.awt.Color(0, 51, 0));
        Ano.setText("2024");
        jPanel1.add(Ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, -1, -1));

        Escola.setFont(new java.awt.Font("Century", 1, 28)); // NOI18N
        Escola.setForeground(new java.awt.Color(71, 117, 71));
        Escola.setText("Instituto Nacional de Aplicação Tecnologica");
        jPanel1.add(Escola, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        Curso.setFont(new java.awt.Font("Informal Roman", 1, 36)); // NOI18N
        Curso.setForeground(new java.awt.Color(18, 50, 2));
        Curso.setText("Curso:");
        jPanel1.add(Curso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        ICON.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframeproject/pngwing.com.png"))); // NOI18N
        ICON.setMaximumSize(new java.awt.Dimension(150, 136));
        ICON.setMinimumSize(new java.awt.Dimension(150, 136));
        ICON.setPreferredSize(new java.awt.Dimension(150, 136));
        jPanel1.add(ICON, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 200, 140));

        Aluno.setBackground(new java.awt.Color(204, 204, 204));
        Aluno.setFont(new java.awt.Font("Informal Roman", 1, 36)); // NOI18N
        Aluno.setForeground(new java.awt.Color(20, 42, 2));
        Aluno.setText("Aluno:");
        jPanel1.add(Aluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 110, -1));

        Serie.setFont(new java.awt.Font("Informal Roman", 1, 36)); // NOI18N
        Serie.setForeground(new java.awt.Color(23, 50, 1));
        Serie.setText("Serie:");
        jPanel1.add(Serie, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 90, 30));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframeproject/hogwarts_legacy___ever_edition_4k_wallpaper_by_aksensei_dg29l08-fullview.jpg"))); // NOI18N
        Background.setText("bck");
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 890, 650));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cancelarActionPerformed

    private void okayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okayActionPerformed
        JOptionPane.showMessageDialog(null,"Nome do aluno: " + aluno.getText() + "\n Série: " + serie.getText() + "\n Curso: " + curso.getText()+ "\n Responsavél: " + resp + "\n Idade: " + idade);
        System.exit(0);
    }//GEN-LAST:event_okayActionPerformed

    private void alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alunoActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_alunoActionPerformed

    private void cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cursoActionPerformed

    private void NatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NatalActionPerformed
         //Formatar Data de String para Date e vice-versa
        Date dataNascimento = null;
        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");
        formatoData.setLenient(false);
        Scanner s = new Scanner(JOptionPane.showInputDialog(null, "Informe a data de nascimento no formato dd/MM/yyyy: "));
        String teclado = s.next();
        try {
            dataNascimento = formatoData.parse(teclado);
            JOptionPane.showMessageDialog(null, "Data Informada sem formatação: " + dataNascimento);
            JOptionPane.showMessageDialog(null, "Data Informada com formatação: " + formatoData.format(dataNascimento));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Data Inválida!");
        }
        
        //Calcular Idade
        Calendar hoje = Calendar.getInstance();
        hoje.getTime();
        
        Calendar dataNasc = Calendar.getInstance();
        dataNasc.setTime(dataNascimento);
        
        idade = hoje.get(Calendar.YEAR) - dataNasc.get(Calendar.YEAR);
        
        if (hoje.get(Calendar.MONTH) < dataNasc.get(Calendar.MONTH)) {
            idade--;
         }
        if (idade <18){
           resp = JOptionPane.showInputDialog("Menor de idade\n" + "Insira o nome do responsável");        }
    }//GEN-LAST:event_NatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame4Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame4Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame4Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame4Project.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrame4Project().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Aluno;
    private javax.swing.JLabel Ano;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Curso;
    private javax.swing.JLabel Escola;
    private javax.swing.JLabel ICON;
    private javax.swing.JButton Natal;
    private javax.swing.JLabel Serie;
    private javax.swing.JTextField aluno;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField curso;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton okay;
    private javax.swing.JTextField serie;
    // End of variables declaration//GEN-END:variables
}
